# 

stages:          # List of stages for jobs, and their order of execution
  - pack_and_publish

#######################################################################################################################
##### Pack and publish
#######################################################################################################################
pack+publish:
  stage: pack_and_publish

  when: manual
  allow_failure: false

  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]

  script:
#    # Retrieve BUILD_TAG
#    - export BUILD_TAG=$(cat build.tag)
#    - echo $BUILD_TAG
    # Build, push and tag
    - mkdir -p /kaniko/.docker
    - cp $DOCKER_AUTH_CONFIG /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - /kaniko/executor --context . --dockerfile test-image/Dockerfile --destination jfrog.svc.cscs.ch/ws-vcmsa/slurm-container.test-image
#    - /kaniko/executor --context . --dockerfile test-image/Dockerfile --destination jfrog.svc.cscs.ch/ws-vcmsa/slurm-container/slurm-container.test-image
#    - /kaniko/executor --context . --dockerfile debian/Dockerfile --destination jfrog.svc.cscs.ch/ws-vcmsa/slurm-container/slurm-container.debian:$BUILD_TAG
#    - /kaniko/executor --context . --dockerfile suse/Dockerfile --destination jfrog.svc.cscs.ch/ws-vcmsa/slurm-container/slurm-container.suse:$BUILD_TAG


#  artifacts:
#    expose_as: 'Files'
#    expire_in: 1 week # Allow promotion of an image after several days
#    paths:
#      - build.tag

