name: Docker Image CI Test

on:
  workflow_dispatch:
    
jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 20.11.9
          - 21.08.8-2
          - 22.05.5

    env:
      tag:      ghcr.io/eth-cscs/slurm-container-${{ matrix.version }}:latest
      context:  .github/workflows/cscs/slurm-${{ matrix.version }}

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build the Docker image
      run: docker build ${{ env.context }} --tag ${{ env.tag }}
    - name: Push Docker Image
      run: docker push ${{ env.tag }}
